version: '3.6'
services:
  lpcmmariadb:
    build:
      context: ./
      dockerfile: ./Environment/lp_cm_mariadb/Dockerfile
    restart: always
    networks:
      lp_cm_net:
        ipv4_address: 172.34.128.2
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=notSecret
      - MYSQL_ROOT_PASSWORD=notSecret
      - TZ=Europe/Berlin
    volumes:
      - rpll_mariadb_volume:/var/lib/mysql
    ports:
      - "3333:3306"
  lpcmnginx:
    depends_on:
      - lpcmbackend
    build:
      context: ./
      dockerfile: ./Environment/lp_cm_nginx/Dockerfile
    networks:
      lp_cm_net:
        ipv4_address: 172.34.128.3
    ports:
      - '8880:80'
  lpcmbackend:
    depends_on:
      - lpcmmariadb
    build:
      context: ./
      dockerfile: ./Environment/lp_cm_backend/Dockerfile
    restart: always
    networks:
      lp_cm_net:
        ipv4_address: 172.34.128.4
    environment:
      - CHARACTERS_URL=mysql://root:vagrant@172.17.0.1/characters
      - LP_CONSENT_URL=mysql://root:notSecret@lpcmmariadb/lp_consent
      - ROCKET_DATABASES={characters={url="mysql://root:vagrant@172.17.0.1/characters"}, lp_consent={url="mysql://root:notSecret@lpcmmariadb/lp_consent"}}
      - LP_API_TOKEN=6bc2dd2398e3cf5882a076fc081265db55a8e96e4c87361c478bdf031ad21c907ec06a68de295c4f18a279a678344cbbb079e6a0b56023bbd4a4b44ffad4a41d
      - URL_AUTHORIZATION_ENDPOINT=http://localhost:8001/token_validator
      - CHARACTER_FETCH_INTERVAL_IN_SEC=600
      - EXPANSION_ID=2
      - UID_SALT=SomeSalt
      - OPT_IN_MODE=false

networks:
  lp_cm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.34.0.1/16

volumes:
  rpll_mariadb_volume:
