version: '3.6'
services:
    lpcmmariadb:
        build: ./Environment/lp_cm_mariadb
        networks:
          - lp_cm_net
        volumes:
            - ./Database/patches:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=notSecret
            - MYSQL_ROOT_PASSWORD=notSecret
    lpcmnginx:
        build: ./Environment/lp_cm_nginx
        networks:
          - lp_cm_net
        ports:
            - '8880:80'
    lpcmwebclient:
        build: ./Environment/lp_cm_webclient
        networks:
          - lp_cm_net
    lpcmbackend:
        build: ./Environment/lp_cm_backend
        networks:
          - lp_cm_net
        environment:
            - LP_CONSENT_MYSQL_DNS=mysql://root:notSecret@lpcmmariadb/
            - CHARACTER_MYSQL_DNS=mysql://root:secret@127.0.0.1/
            - LP_API_TOKEN=c7719277bbf252d90427afa088cdaa11898ffcfee09ff073869a61aaff88b686fe3da602642d76ccfbc532c6756cc678df7e5368c0aede8fe83290399699b36e
            - URL_AUTHORIZATION_ENDPOINT=http://localhost:8001/token_validator
            - CHARACTER_FETCH_INTERVAL_IN_SEC=60
            - EXPANSION_ID=2
            - UID_SALT=SomeSalt

networks:
  lp_cm_net:
    driver: bridge
