version: '3.6'
services:
    lpcmmariadb:
        build: lp_cm_mariadb
        networks:
          - lp_cm_net
        volumes:
            - ./../LegacyPlayersV3/Exporter/Database:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=notSecret
            - MYSQL_ROOT_PASSWORD=notSecret
    lpcmnginx:
        build: lp_cm_nginx
        networks:
          - lp_cm_net
        ports:
            - '8880:80'
    lpcmwebclient:
        build: lp_cm_webclient
        networks:
            - lp_cm_net
    lpcmbackend:
        build: lp_cm_backend
        networks:
          - lp_cm_net
        environment:
            - LP_CONSENT_MYSQL_DNS=mysql://root:notSecret@lpcmmariadb/lp_consent
            - CHARACTER_MYSQL_DNS=mysql://root:vagrant@172.17.0.1/characters
            - LP_API_TOKEN=YourAPIToken
            - URL_AUTHORIZATION_ENDPOINT=http://localhost:8001/token_validator
            - CHARACTER_FETCH_INTERVAL_IN_SEC=60
            - EXPANSION_ID=2
            - UID_SALT=SomeSalt

networks:
  lp_cm_net:
    driver: bridge
