version: '3.6'
services:
  lpcmmariadb:
    build: lp_cm_mariadb
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=notSecret
      - MYSQL_ROOT_PASSWORD=notSecret
  lpcmnginx:
    build: lp_cm_nginx
    ports:
      - '8880:80'
  lpcmwebclient:
    build: lp_cm_webclient
  lpcmbackend:
    build: lp_cm_backend
    environment:
      - LP_CONSENT_URL=mysql://root:notSecret@lpcmmariadb/lp_consent
