[package]
name = "validator"
version = "0.1.0"
authors = ["Tom Dymel <tom@dymel.dev>"]

[dependencies]
pwned = "0.2.1"
regex = "*"
lazy_static = "*"

[dev-dependencies]
proptest = "0.9.6"
dotenv = "*"